name: SecDevOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  securite:
    runs-on: ubuntu-latest

    steps:
      # --- SETUP ---
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js (pour Snyk)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installer Snyk
        run: npm install -g snyk

      # --- ANALYSE Snyk SCA ---
      - name: Exécuter l’analyse Snyk (SCA)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --sarif-file-output=snyk-report-SCA.sarif || echo "Pas de dépendances trouvées, SCA ignoré"
      
      # --- ANALYSE Snyk Code (SAST) ---
      - name: Exécuter l’analyse Snyk Code (SAST)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test ./ --sarif-file-output=snyk-report-SAST.sarif || echo "Pas de code analysé"

      # --- UPLOAD DES RAPPORTS ---
      - name: Upload du rapport Snyk Code (SAST)
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report-SAST
          path: snyk-report-SAST.sarif

      - name: Upload du rapport Snyk SCA
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report-SCA
          path: snyk-report-SCA.sarif
